### ISSUE TITLE
Support user-defined custom providers

### ISSUE THREAD

**Issue by naclander** [etu/webpaste.el#21]
It would be nice to let users to define their own custom providesr, for example if they have private pastebins they want to use. A user can then just append the custom provider they defined onto the existing provider list. 

I staretd looking at this, but I think it would take some refactoring, as the current provider list is not defined via `defcustom`, and is tightly integraetd with the way webpaste internals are defined ( using `webpaste-provider`, and `webpaste-providers-success-response-url` ).

**Comment by etu** [comment]
That was one of the original plans. And it used to use defcustom and was
using it up to 1.3.0 as seen here:
https://github.com/etu/webpaste.el/blob/1.3.0/webpaste.el#L218-L283

But it was also very messy when it showed up in the `M-x customize-group
webpaste` interface because it was inline lisp and hard to read and write.
So I just assumed that nobody modified the variable that way because it was
unusable.

It's been hard to make it easy to write providers. Especially for people
that don't know the internals.

Maybe it should be more documented? Like one org file explaining all the
parameters required. How to test stuff and how to append it to the list of
providers?

**Comment by naclander** [comment]
I think I'm fine with users having to read documentation in order to wrote providers. Althoguh I think a lot of it is self-explanatory just by looking at some of the simple providers. A lot of them generally follow the same form  of `curl -F 'name=value' address.com` anyway.

The problem right now is that this is impossible to do without opening up webpaste.el, and evaluating the buffer ( since otherwise `webpaste-providers-alist` isn't loaded ). 

I think I'm more ok with showing an example of how one would create a provider, and then append it to `webpaste-providers-alist`. We can point them at the docstring for `webpaste-provider` and at the `request.el` package if they want understand more of the internals. 

So I think we should probably change the format of webpaste-providers-alist so that a user can just append something like

``` elisp
( "ix.io"
  (( :uri "http://ix.io")
   ( :post-field "f:1")
   ( :lang-uri-seperator "/" )
   ( :lang-overrides '((emacs-lisp-mode . "elisp")))
   ( :succses-lambda 'webpaste-providers-success-location-header))))
```
Which is mostly self-explanatory and lets users just define their own providers and then call `add-to-list` to use them.

**Comment by etu** [comment]
One can do:

(require 'webpaste)

In any elisp file, or config, to load webpaste.el. Then you have access to
webpaste-providers-alist and everything. And it's quite common that one
need to run require on something to load it and it's not uncommon that
people have require's of things in their configs.

But I must say that that format you suggested is pretty. I'd believe that
it's not pretty to store lambdas in variables too much (like it is today).

And with a format like that, one could build a function named something
like webpaste-get-provider-by-name which looks it up in the list and runs
webpaste-provider and returns it. That would as well clean up many tests
that uses the providers since the current method to get a provider is (cadr
(assoc "ix.io" webpaste-providers-alist)).

**Comment by naclander** [comment]
Ah right, I forgot I needed to require webpaste before using variables defined there. 

I think then maybe all we need to do is in the readme let people know they _can_ add providers, if they choose? For example, we can say:

To add a new provider, you can add

```elisp
(require 'webpaste)
(add-to-list 'webpaste-providers-alist
 `("example.provider"
   ,(webpaste-provider
     :uri "http://example.provider/"
     :post-field "value"
     :lang-uri-separator "/"
     :lang-overrides '((emacs-lisp-mode . "elisp"))
     :success-lambda 'webpaste-providers-success-returned-string)))
```
to your config.

This is uglier than my above example, but at least it works in webpaste's current form. We can hold off on that if you think we're likely to refactor the provider alist soon.

re: the ugly alist format ( which I agree is ugly ), we could always just consider using a [Hash Table](https://www.gnu.org/software/emacs/manual/html_node/elisp/Hash-Access.html#Hash-Access). Not for performance per say ( since we have too few providers for it to matter ) but because the API is way cleaner.

**Comment by etu** [comment]
I've havent read about hashtables before. I must say I like how they are
used. It's certanly simpler than using alists. But, I think I find alists
more aproachable by most people since it's more common.

I also find the hashtables less discoverable, I can eval an alist and get
the entire content in a clean syntax.

So I think I prefer your example above, need to think about this. But I
think we could refactor this fairly soon, so I don't see the need to
document this too much yet.

But when documented, I think it would be a good idea to look through the
documentation written in the code and then clarify some parts if needed and
put it in an org-file to make it more approachable for people who aren't
fluent in reading the documentation in Emacs. I think many people aren't
aware of how to read up on such documentation and tend to go to the closest
search engine for answers...

**Comment by naclander** [comment]
I mainly agree with everything you've said.

As for the org file containing the docementation, that should probably the README since I don't think this project is big enought yet to need a seperate "usage" file. The user can also get all the information they need about webpaste from one file.

**Comment by etu** [comment]
Yeah, for sure :)

But I still like the idea of a new format of the alist before making the
documentation "too easy" to find for newcomers to not break it more than
necessary :)

**Comment by etu** [comment]
So I came up with a slightly different format very much like yours that is easier to read and easier to parse:
```elisp
(defvar webpaste-providers-alist-test
  '(("ptpb.pw"
     :uri "https://ptpb.pw/"
     :post-field "c"
     :lang-uri-separator "/"
     :lang-overrides ((emacs-lisp-mode . "elisp"))
     :success-lambda webpaste-providers-success-location-header)
    ("ix.io"
     :uri "http://ix.io/"
     :post-field "f:1"
     :lang-uri-separator "/"
     :lang-overrides ((emacs-lisp-mode . "elisp"))
     :success-lambda webpaste-providers-success-returned-string))
  "Providers.")
```

Provider creation would then look like this:
```elisp
(apply 'webpaste-provider (cdr (assoc "ptpb.pw" webpaste-providers-alist-test)))
```

**Comment by naclander** [comment]
Yea I think that's much more readable.

**Comment by etu** [comment]
The implementation is now merged in https://github.com/etu/webpaste.el/commit/26a8035f5e5c828435eb65d440b2ebce5e5a346e

The documentation is not updated yet though :)

**Comment by naclander** [comment]
Looks good!
