### ISSUE TITLE
MELPA recipe still using "master"?

### ISSUE THREAD

**Issue by dsedivec** [etu/webpaste.el#54]
I think maybe the MELPA recipe is still using `master`?  MELPA showing last commit was August.  I think maybe it needs to have `:branch "main"` added?

**Comment by etu** [comment]
Oh, I haven't thought of that when changing the branch name, however, it shouldn't have held any important changes back since it's mostly been readme changes and other meta files changes to prepare for NonGNU ELPA inclusion.

So I'll keep this issue open for a bit until I resolve it with melpa (which I probably should do as well as the inclusion to NonGNU ELPA).

Thanks for the heads up :)

**Comment by etu** [comment]
So I have looked in to this, the recipe looks like the following: https://github.com/melpa/melpa/commit/13847d91c1780783e516943adee8a3530c757e17

No branch specified, according to the readme, I shouldn't have to specify the branch name as long as it's the default branch (which it is): https://github.com/melpa/melpa/blob/master/README.md#recipe-format

But as you're saying, it seems to be stuck, so it's probably cloned somewhere using master. I'm assuming it would help to add the `:branch "main"` to the recipe.

The package is now more up to date in NonGNU ELPA, but I'm planning to keep it in MELPA as well since they provide non-tagged-as-stable releases as well.

I've sent a PR to melpa for this at least.

**Comment by etu** [comment]
This seems to be resolved now :)
